apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-crocodile-stress-test
spec:
  parallelism: 4
  separate: true
  cleanup: post
  script:
    configMap:
      name: k6-crocodile-stress-test
      file: k6-crocodile-stress-test.js
