---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-2tb-m2-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-mnt-2tb-m2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-2tb-m2-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: hostpath-2tb-m2-claim
